export const ACTION_GET_COUNTRY_SAGA = "ACTION_GET_COUNTRY_SAGA"
export const ACTION_GET_COUNTRY_SUCCESS = "ACTION_GET_COUNTRY_SUCCESS"
export const ACTION_GET_COUNTRY_FAIL = "ACTION_GET_COUNTRY_FAIL"
export const ACTION_GET_COUNTRY_SELECTED = "ACTION_GET_COUNTRY_SELECTED"

export const ACTION_GET_SUMMARY_SAGA = "ACTION_GET_SUMMARY_SAGA"
export const ACTION_GET_SUMMARY_SUCCESS = "ACTION_GET_SUMMARY_SUCCESS"
export const ACTION_GET_SUMMARY_FAIL = "ACTION_GET_SUMMARY_FAIL"

export const ACTION_GET_SAGA_COUNTRY_LIVE = "ACTION_GET_SAGA_COUNTRY_LIVE";
export const ACTION_GET_SUCCESS_COUNTRY_LIVE = "ACTION_GET_SUCCESS_COUNTRY_LIVE";
export const ACTION_GET_FAIL_COUNTRY_LIVE = "ACTION_GET_FAIL_COUNTRY_LIVE";